
strictness: high

max-line-length: 120

member-warnings: true

test-warnings: true

doc-warnings: true

pylint:
  options:
    init-import: true
    dummy-variables-rgx: _$|dummy|___

  disable:
    - invalid-name
    - trailing-newlines
    - no-self-use
    - too-many-branches
    - too-many-arguments
    - too-many-instance-attributes
    - too-many-locals
    - too-many-lines
    - redefined-outer-name
    - redefined-builtin

mccabe:
  run: false

pep8:
  disable:
    - E128

pep257:
  disable:
    - D200
    - D202
    - D203
    - D204
    - D213
